<?php

namespace App\Filament\App\Resources\WorkSessionResource\Pages;

use App\Filament\App\Resources\WorkSessionResource;
use App\Models\Task;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Facades\URL;

class CreateWorkSession extends CreateRecord
{
    protected static string $resource = WorkSessionResource::class;

    public $redirectUrl = null;

    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub

        if (request()->get('task')) {
            $task = Task::find(request()->get('task'));

            if ($task) {
                $this->form->fill(
                    self::getFillFormArray($task)
                );
            }

            $this->redirectUrl = URL::previous();
        }
    }

    protected function getRedirectUrl(): string
    {
        return $this->redirectUrl ?? parent::getRedirectUrl();
    }

    public static function getFillFormArray(Task $task): array
    {
        $fill = [
            'title' => $task->title,
            'start' => now(),
            'rate' => 0,
            'is_running' => true,
        ];

        if ($task->client_id) {
            $fill['client'] = $task->client_id;
        }

        if ($task->project_id) {
            $fill['project'] = $task->project_id;
        }

        if ($task->id) {
            $fill['task'] = $task->id;
        }

        return $fill;
    }
}
