<?php

namespace App\Filament\App\Resources\WorkSessionResource\Pages;

use App\Filament\App\Resources\WorkSessionResource;
use App\Models\Task;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Facades\URL;

class CreateWorkSession extends CreateRecord
{
    protected static string $resource = WorkSessionResource::class;

    public $redirectUrl = null;

    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub

        if (request()->get('task')) {
            $task = Task::find(request()->get('task'));

            $this->form->fill([
                'title' => $task->title,
                'client' => $task->client_id,
                'project' => $task->project_id,
                'task' => $task->id,
                'start' => now(),
                'rate' => 0,
                'is_running' => true,
            ]);

            $this->redirectUrl = URL::previous();
        }
    }

    protected function getRedirectUrl(): string
    {
        return $this->redirectUrl ?? parent::getRedirectUrl();
    }
}
